services:
  - type: web
    name: ecommerce-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: API_URL
        value: https://your-app-name.onrender.com
    healthCheckPath: /health
